### ISSUE TITLE
cannot generate pages

### ISSUE THREAD

**Issue by ufoym** [17/hexo-theme-strict#3]
# 错误还原步骤

$ npm install hexo -g
$ npm install hexo-renderer-jade --save
$ hexo init blog
$ cd blog
$ git clone git@github.com:unmric/hexo-theme-strict.git themes/strict
$ hexo generate
# 出错提示

[error] TypeError: undefined is not a function
TypeError: undefined is not a function
    at C:\Users\u\AppData\Roaming\npm\node_modules\hexo\lib\core\render.js:181:7

```
at fn (C:\Users\u\AppData\Roaming\npm\node_modules\hexo\node_modules\async\l
```

ib\async.js:579:34)
    at Object._onImmediate (C:\Users\u\AppData\Roaming\npm\node_modules\hexo\nod
e_modules\async\lib\async.js:495:34)
    at processImmediate [as _immediateCallback](timers.js:330:15)

C:\Users\u\AppData\Roaming\npm\node_modules\hexo\lib\core\render.js:181
      renderer({path: source, text: data._content}, locals, function(err, resu
      ^
TypeError: undefined is not a function
    at C:\Users\u\AppData\Roaming\npm\node_modules\hexo\lib\core\render.js:181:7

```
at fn (C:\Users\u\AppData\Roaming\npm\node_modules\hexo\node_modules\async\l
```

ib\async.js:579:34)
    at Object._onImmediate (C:\Users\u\AppData\Roaming\npm\node_modules\hexo\nod
e_modules\async\lib\async.js:495:34)
    at processImmediate [as _immediateCallback](timers.js:330:15)

**Comment by 17** [comment]
以上步骤在 Mac, Windows and Linux 中均不能还原相似错误.

---

依照出错信息, 这是在 hexo 获取模板引擎中出错. ( [`hexo.extend.renderer.get`](//github.com/tommy351/hexo/blob/master/lib/core/render.js#L181) 得到了`undefined`)
按照以上思路. 应检测你的本地环境中 `hexo-renderer-jade` 的完整度, 或尝试清空 NPM 缓存.
good luck! ; )

**Comment by ufoym** [comment]
谢谢啦~
